//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HspDecompiler.Core.Resources
{
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Strings() { }

        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("HspDecompiler.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Dictionary
        internal static string DictionaryLoadSuccess => ResourceManager.GetString("DictionaryLoadSuccess", resourceCulture);
        internal static string DictionaryLoadFailed => ResourceManager.GetString("DictionaryLoadFailed", resourceCulture);
        internal static string DictionaryLoadError => ResourceManager.GetString("DictionaryLoadError", resourceCulture);
        internal static string DictionaryNotInitialized => ResourceManager.GetString("DictionaryNotInitialized", resourceCulture);

        // DPM extraction
        internal static string SearchingDpmHeader => ResourceManager.GetString("SearchingDpmHeader", resourceCulture);
        internal static string DpmHeaderNotFound => ResourceManager.GetString("DpmHeaderNotFound", resourceCulture);
        internal static string DpmNoFiles => ResourceManager.GetString("DpmNoFiles", resourceCulture);
        internal static string AllFilesEncrypted => ResourceManager.GetString("AllFilesEncrypted", resourceCulture);
        internal static string FileEncrypted => ResourceManager.GetString("FileEncrypted", resourceCulture);
        internal static string FileAlreadyExists => ResourceManager.GetString("FileAlreadyExists", resourceCulture);
        internal static string FileSeekFailed => ResourceManager.GetString("FileSeekFailed", resourceCulture);
        internal static string FileSaveFailed => ResourceManager.GetString("FileSaveFailed", resourceCulture);
        internal static string DirectoryCreateFailed => ResourceManager.GetString("DirectoryCreateFailed", resourceCulture);
        internal static string ExtractionCancelled => ResourceManager.GetString("ExtractionCancelled", resourceCulture);
        internal static string ExtractionComplete => ResourceManager.GetString("ExtractionComplete", resourceCulture);

        // Decryption
        internal static string DecryptingFile => ResourceManager.GetString("DecryptingFile", resourceCulture);
        internal static string DecryptionFailed => ResourceManager.GetString("DecryptionFailed", resourceCulture);
        internal static string BufferSizeTooSmall => ResourceManager.GetString("BufferSizeTooSmall", resourceCulture);
        internal static string InsufficientDecryptionInfo => ResourceManager.GetString("InsufficientDecryptionInfo", resourceCulture);

        // Pipeline
        internal static string ReadingFile => ResourceManager.GetString("ReadingFile", resourceCulture);
        internal static string Decompiling => ResourceManager.GetString("Decompiling", resourceCulture);
        internal static string DecompileComplete => ResourceManager.GetString("DecompileComplete", resourceCulture);
        internal static string OutputtingTo => ResourceManager.GetString("OutputtingTo", resourceCulture);
        internal static string OutputComplete => ResourceManager.GetString("OutputComplete", resourceCulture);
        internal static string AnalysisComplete => ResourceManager.GetString("AnalysisComplete", resourceCulture);
        internal static string UnrecognizedFileFormat => ResourceManager.GetString("UnrecognizedFileFormat", resourceCulture);
        internal static string NotHsp2OrHsp3 => ResourceManager.GetString("NotHsp2OrHsp3", resourceCulture);

        // Decoder phases
        internal static string AnalyzingHeader => ResourceManager.GetString("AnalyzingHeader", resourceCulture);
        internal static string AnalyzingPreprocessor => ResourceManager.GetString("AnalyzingPreprocessor", resourceCulture);
        internal static string AnalyzingData => ResourceManager.GetString("AnalyzingData", resourceCulture);
        internal static string LexicalAnalysis => ResourceManager.GetString("LexicalAnalysis", resourceCulture);
        internal static string SyntacticAnalysis => ResourceManager.GetString("SyntacticAnalysis", resourceCulture);
        internal static string CreatingOutputFile => ResourceManager.GetString("CreatingOutputFile", resourceCulture);
        internal static string UnexpectedError => ResourceManager.GetString("UnexpectedError", resourceCulture);

        // Error log
        internal static string ErrorLogWritten => ResourceManager.GetString("ErrorLogWritten", resourceCulture);
        internal static string CodeNotFullyDecompiled => ResourceManager.GetString("CodeNotFullyDecompiled", resourceCulture);

        // Table headers
        internal static string EncryptedYes => ResourceManager.GetString("EncryptedYes", resourceCulture);
        internal static string EncryptedNo => ResourceManager.GetString("EncryptedNo", resourceCulture);
        internal static string ElapsedHeader => ResourceManager.GetString("ElapsedHeader", resourceCulture);
        internal static string ProcessingContent => ResourceManager.GetString("ProcessingContent", resourceCulture);

        // Fatal errors
        internal static string FatalErrorCaught => ResourceManager.GetString("FatalErrorCaught", resourceCulture);
        internal static string CriticalError => ResourceManager.GetString("CriticalError", resourceCulture);

        // Header validation
        internal static string FileHeaderMissing => ResourceManager.GetString("FileHeaderMissing", resourceCulture);
        internal static string InvalidFileFormat => ResourceManager.GetString("InvalidFileFormat", resourceCulture);
        internal static string CompiledWithHsp2OrEarlier => ResourceManager.GetString("CompiledWithHsp2OrEarlier", resourceCulture);
        internal static string HeaderAnalysisFailed => ResourceManager.GetString("HeaderAnalysisFailed", resourceCulture);
        internal static string UnexpectedErrorDuringHeaderAnalysis => ResourceManager.GetString("UnexpectedErrorDuringHeaderAnalysis", resourceCulture);
        internal static string UnexpectedErrorDuringStreamRead => ResourceManager.GetString("UnexpectedErrorDuringStreamRead", resourceCulture);
        internal static string UnrecoverableErrorDuringLabelRead => ResourceManager.GetString("UnrecoverableErrorDuringLabelRead", resourceCulture);
        internal static string HeaderFileSizeExceedsActual => ResourceManager.GetString("HeaderFileSizeExceedsActual", resourceCulture);
        internal static string HeaderRegionStartExceedsFileSize => ResourceManager.GetString("HeaderRegionStartExceedsFileSize", resourceCulture);
        internal static string HeaderRegionEndExceedsFileSize => ResourceManager.GetString("HeaderRegionEndExceedsFileSize", resourceCulture);

        // Header region names
        internal static string RegionCode => ResourceManager.GetString("RegionCode", resourceCulture);
        internal static string RegionLiteral => ResourceManager.GetString("RegionLiteral", resourceCulture);
        internal static string RegionLabel => ResourceManager.GetString("RegionLabel", resourceCulture);
        internal static string RegionDll => ResourceManager.GetString("RegionDll", resourceCulture);
        internal static string RegionFunction => ResourceManager.GetString("RegionFunction", resourceCulture);
        internal static string RegionPlugin => ResourceManager.GetString("RegionPlugin", resourceCulture);
        internal static string RegionParameter => ResourceManager.GetString("RegionParameter", resourceCulture);

        // AxData validation
        internal static string ArgumentNullReader => ResourceManager.GetString("ArgumentNullReader", resourceCulture);
        internal static string ArgumentNullDictionary => ResourceManager.GetString("ArgumentNullDictionary", resourceCulture);
        internal static string LoadStartNotCalled => ResourceManager.GetString("LoadStartNotCalled", resourceCulture);
        internal static string HeaderNotLoaded => ResourceManager.GetString("HeaderNotLoaded", resourceCulture);

        // Syntactic analysis
        internal static string RpnConversionFailed => ResourceManager.GetString("RpnConversionFailed", resourceCulture);
        internal static string StructNotInHspSpec => ResourceManager.GetString("StructNotInHspSpec", resourceCulture);
        internal static string AnalysisFailedEndNotStored => ResourceManager.GetString("AnalysisFailedEndNotStored", resourceCulture);
        internal static string AnalysisFailedScopeEndExceedsCode => ResourceManager.GetString("AnalysisFailedScopeEndExceedsCode", resourceCulture);
        internal static string AnalysisFailedScopeEndMidLine => ResourceManager.GetString("AnalysisFailedScopeEndMidLine", resourceCulture);

        // CodeTokenFactory
        internal static string ExpressionStackEmpty => ResourceManager.GetString("ExpressionStackEmpty", resourceCulture);
        internal static string ExpressionInvalidElement => ResourceManager.GetString("ExpressionInvalidElement", resourceCulture);
        internal static string LiteralExpressionStackEmpty => ResourceManager.GetString("LiteralExpressionStackEmpty", resourceCulture);
        internal static string LiteralExpressionInvalidElement => ResourceManager.GetString("LiteralExpressionInvalidElement", resourceCulture);
        internal static string ArgumentStackEmpty => ResourceManager.GetString("ArgumentStackEmpty", resourceCulture);
        internal static string FunctionStackEmpty => ResourceManager.GetString("FunctionStackEmpty", resourceCulture);
        internal static string FunctionInvalidStart => ResourceManager.GetString("FunctionInvalidStart", resourceCulture);
        internal static string VariableStackEmpty => ResourceManager.GetString("VariableStackEmpty", resourceCulture);
        internal static string VariableInvalidStart => ResourceManager.GetString("VariableInvalidStart", resourceCulture);
        internal static string OperatorStackEmpty => ResourceManager.GetString("OperatorStackEmpty", resourceCulture);
        internal static string OperatorInvalidElement => ResourceManager.GetString("OperatorInvalidElement", resourceCulture);

        // LogicalLineFactory
        internal static string CannotDetermineLeadToken => ResourceManager.GetString("CannotDetermineLeadToken", resourceCulture);
        internal static string McallInvalidStart => ResourceManager.GetString("McallInvalidStart", resourceCulture);
        internal static string McallInconvertibleFormat => ResourceManager.GetString("McallInconvertibleFormat", resourceCulture);
        internal static string McallUnexpectedToken => ResourceManager.GetString("McallUnexpectedToken", resourceCulture);
        internal static string OnBranchInvalidStart => ResourceManager.GetString("OnBranchInvalidStart", resourceCulture);
        internal static string OnBranchUnexpectedToken => ResourceManager.GetString("OnBranchUnexpectedToken", resourceCulture);
        internal static string AssignmentNoOperator => ResourceManager.GetString("AssignmentNoOperator", resourceCulture);
        internal static string AssignmentUnexpectedToken => ResourceManager.GetString("AssignmentUnexpectedToken", resourceCulture);
        internal static string IfBranchInvalidStart => ResourceManager.GetString("IfBranchInvalidStart", resourceCulture);
        internal static string IfBranchUnexpectedToken => ResourceManager.GetString("IfBranchUnexpectedToken", resourceCulture);
        internal static string CommandUnexpectedToken => ResourceManager.GetString("CommandUnexpectedToken", resourceCulture);

        // Misc
        internal static string OperatorPriorityOnNonOperator => ResourceManager.GetString("OperatorPriorityOnNonOperator", resourceCulture);
        internal static string UnsupportedType => ResourceManager.GetString("UnsupportedType", resourceCulture);
    }
}
