//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HspDecompiler.Gui.Resources
{
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Strings() { }

        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("HspDecompiler.Gui.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Menu
        internal static string MenuFile => ResourceManager.GetString("MenuFile", resourceCulture);
        internal static string MenuOpen => ResourceManager.GetString("MenuOpen", resourceCulture);
        internal static string MenuExit => ResourceManager.GetString("MenuExit", resourceCulture);
        internal static string MenuHelp => ResourceManager.GetString("MenuHelp", resourceCulture);
        internal static string MenuAbout => ResourceManager.GetString("MenuAbout", resourceCulture);

        // DataGrid columns
        internal static string ColumnFilename => ResourceManager.GetString("ColumnFilename", resourceCulture);
        internal static string ColumnEncrypted => ResourceManager.GetString("ColumnEncrypted", resourceCulture);
        internal static string ColumnOffset => ResourceManager.GetString("ColumnOffset", resourceCulture);
        internal static string ColumnFileSize => ResourceManager.GetString("ColumnFileSize", resourceCulture);

        // Window titles
        internal static string WindowTitle => ResourceManager.GetString("WindowTitle", resourceCulture);
        internal static string AboutTitle => ResourceManager.GetString("AboutTitle", resourceCulture);

        // File picker
        internal static string OpenFileTitle => ResourceManager.GetString("OpenFileTitle", resourceCulture);
        internal static string HspFilesFilter => ResourceManager.GetString("HspFilesFilter", resourceCulture);
        internal static string AllFilesFilter => ResourceManager.GetString("AllFilesFilter", resourceCulture);

        // Messages
        internal static string FailedToLoadDictionary => ResourceManager.GetString("FailedToLoadDictionary", resourceCulture);
        internal static string ErrorFormat => ResourceManager.GetString("ErrorFormat", resourceCulture);
    }
}
